# Site settings
title: "RootedLABs"
email:
description: "Decentralized Food, For Everyone"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
